# Based on https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: Build application
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v2

      - name: ğŸ— Setup
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'

      - name: âš™ï¸ Install
        run: npm ci

      - name: ğŸ›  Build
        run: npm run build:production

      - name: ğŸ“‚ Upload build (to artifacts)
        uses: actions/upload-artifact@v3
        with:
          name: covid-stats-front
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸ–¥ Download built WEB (to artifacts)
        uses: actions/download-artifact@v3
        with:
          name: covid-stats-front

      - name: ğŸ“‚ Upload static files to the server
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./covid/
          remoteDir: ./
          options: --exclude .htaccess --exclude robots.txt --delete --delete-first --ascii
